// import { hasUncaughtExceptionCaptureCallback } from "process"

// test('sum 2+2', ()=> {
//     hasUncaughtExceptionCaptureCallback(2+2).toBe(4)
// });